### ISSUE TITLE
Additions to setup-apple-time-machine-network-drive-with-samba-on-ubuntu-22.04

### ISSUE THREAD

**Issue by paul-hammant** [sjohner/jhnr.ch#1]
The `timemachine` dir on the destination FS needs to be chown'd to the user that's connecting.
Might also need to be `chmod -R ug+rw`

For some reason my setup following your guide didn't have those, and I encountered this dialog https://apple.stackexchange.com/questions/127665/you-do-not-have-the-necessary-read-write-and-append-privileges-on-the-selected

Great article - thanks for writing it.

**Comment by sjohner** [comment]
Thank you @paul-hammant for the hint. Updated the post with a hint about the fs permissions.
